services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=loans
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
    - PORT=3001
    networks:
      - app_network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loans
    ports:
      - "5432:5432"
    networks:
      - app_network

  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
