# Usa a imagem oficial do Node.js
FROM node:18

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos do projeto
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante do código
COPY . .

# Gera a build de produção
RUN npm run build 

# Expondo a porta da API
EXPOSE 3000

# Comando para rodar a aplicação em produção
CMD ["npm", "run", "start"] 
